name: Find or Create Linear Issue in Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

permissions:
  pull-requests: write

jobs:
  create-linear-issue-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Find or create a Linear Issue
        uses: ctriolo/action-find-or-create-linear-issue@v1
        with:
          github-token: ${{secrets.GH_TOKEN}}
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-team-key: 'SC'
