name: Pre Release
on:
  push:
    branches:
      - dev
jobs:
  release:
    name: PreRelease
    runs-on: ubuntu-latest
    steps:
      - name: '📝Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }} # Add this line

      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV

      - name: 'Setup 🟢Node ${{ env.node_version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.node_version }}'
          cache: 'yarn'

      - name: '📂 Install dependencies'
        run: yarn install --frozen-lockfile --ignore-scripts --omit=dev

      - name: 'Delete existing tag if present'
        run: |
          git tag -d v1.0.0-dev.48 || true
          git push --delete origin v1.0.0-dev.48 || true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: '🚀 PreRelease'
        env:
          # Use GH_TOKEN for semantic-release
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Add both to be safe
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn build:release
